import type { KnowledgeDomain } from "../types";

export const economicIndicators: KnowledgeDomain = {
  id: "economic-indicators",
  title: "Economic Indicators",
  summary: "High-impact macro releases the market watches, with typical cadence and source.",
  entries: [
    {
      id: "cpi",
      domain: "economic-indicators",
      category: "reference",
      title: "Consumer Price Index (CPI)",
      summary: "Monthly headline and core inflation from BLS.",
      data: { source: "BLS", frequency: "monthly" },
      tags: ["inflation"],
    },
    {
      id: "ppi",
      domain: "economic-indicators",
      category: "reference",
      title: "Producer Price Index (PPI)",
      summary: "Wholesale price inflation from BLS.",
      data: { source: "BLS", frequency: "monthly" },
      tags: ["inflation"],
    },
    {
      id: "pce",
      domain: "economic-indicators",
      category: "reference",
      title: "PCE Price Index",
      summary: "The Fed's preferred inflation measure from BEA.",
      data: { source: "BEA", frequency: "monthly" },
      tags: ["inflation", "fed"],
    },
    {
      id: "nfp",
      domain: "economic-indicators",
      category: "reference",
      title: "Nonfarm Payrolls (NFP)",
      summary: "Monthly employment change and unemployment rate from BLS.",
      data: { source: "BLS", frequency: "monthly", release: "first Friday" },
      tags: ["employment"],
    },
    {
      id: "gdp",
      domain: "economic-indicators",
      category: "reference",
      title: "GDP",
      summary: "Quarterly advance, second, and third estimates from BEA.",
      data: { source: "BEA", frequency: "quarterly" },
      tags: ["growth"],
    },
    {
      id: "fomc",
      domain: "economic-indicators",
      category: "reference",
      title: "FOMC Meeting & Fed Funds Rate",
      summary: "Eight scheduled meetings per year; statement, projections (SEP), and press conference drive rate expectations.",
      data: { source: "Federal Reserve", frequency: "~6 weeks" },
      tags: ["rates", "fed"],
    },
    {
      id: "ism-pmi",
      domain: "economic-indicators",
      category: "reference",
      title: "ISM Manufacturing / Services PMI",
      summary: "Diffusion indices above/below 50 signal expansion/contraction.",
      data: { source: "ISM", frequency: "monthly" },
      tags: ["survey"],
    },
    {
      id: "retail-sales",
      domain: "economic-indicators",
      category: "reference",
      title: "Retail Sales",
      summary: "Monthly consumer spending from the U.S. Census Bureau.",
      data: { source: "Census", frequency: "monthly" },
      tags: ["consumer"],
    },
  ],
};
