import type { KnowledgeDomain } from "../types";

export const indicators: KnowledgeDomain = {
  id: "indicators",
  title: "Indicators",
  summary: "Common technical indicators with canonical formulas and default parameters.",
  entries: [
    {
      id: "sma",
      domain: "indicators",
      category: "indicator",
      title: "Simple Moving Average (SMA)",
      summary: "Arithmetic mean of the last N closes.",
      data: { formula: "SMA_n = sum(close_{t-n+1..t}) / n", defaults: [20, 50, 200] },
      tags: ["trend"],
    },
    {
      id: "ema",
      domain: "indicators",
      category: "indicator",
      title: "Exponential Moving Average (EMA)",
      summary: "Recency-weighted moving average with smoothing factor 2/(n+1).",
      data: {
        formula: "EMA_t = alpha*close_t + (1-alpha)*EMA_{t-1}, alpha = 2/(n+1)",
        defaults: [9, 21, 50, 200],
      },
      tags: ["trend"],
    },
    {
      id: "rsi",
      domain: "indicators",
      category: "indicator",
      title: "Relative Strength Index (RSI)",
      summary: "Momentum oscillator bounded 0-100.",
      data: { default: 14, overbought: 70, oversold: 30 },
      tags: ["momentum", "oscillator"],
    },
    {
      id: "macd",
      domain: "indicators",
      category: "indicator",
      title: "MACD",
      summary: "EMA(12) - EMA(26) with a 9-period signal line.",
      data: { fast: 12, slow: 26, signal: 9 },
      tags: ["momentum", "trend"],
    },
    {
      id: "bollinger-bands",
      domain: "indicators",
      category: "indicator",
      title: "Bollinger Bands",
      summary: "SMA plus/minus K standard deviations of price.",
      data: { length: 20, mult: 2 },
      tags: ["volatility", "band"],
    },
    {
      id: "vwap",
      domain: "indicators",
      category: "indicator",
      title: "Session VWAP",
      summary: "Intraday volume-weighted average price anchored to the session open.",
      tags: ["benchmark", "intraday"],
    },
    {
      id: "obv",
      domain: "indicators",
      category: "indicator",
      title: "On-Balance Volume (OBV)",
      summary: "Cumulative volume signed by daily close direction.",
      tags: ["volume", "flow"],
    },
    {
      id: "adx",
      domain: "indicators",
      category: "indicator",
      title: "Average Directional Index (ADX)",
      summary: "Trend strength gauge derived from +DI and -DI (Wilder).",
      data: { default: 14, trending: 25 },
      tags: ["trend-strength"],
    },
    {
      id: "stochastic",
      domain: "indicators",
      category: "indicator",
      title: "Stochastic Oscillator",
      summary: "Location of close within the recent range; %K smoothed by %D.",
      data: { k: 14, d: 3 },
      tags: ["momentum", "oscillator"],
    },
    {
      id: "ichimoku",
      domain: "indicators",
      category: "indicator",
      title: "Ichimoku Cloud",
      summary: "Multi-line trend/support system with cloud (Kumo) projection.",
      data: { tenkan: 9, kijun: 26, senkouB: 52 },
      tags: ["trend", "cloud"],
    },
  ],
};
